# Generated by Django 2.1.3 on 2018-11-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='System',
        ),
    ]
