# Generated by Django 2.1.3 on 2018-11-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_auto_20181125_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.IntegerField(primary_key=True, serialize=False)),
                ('crTime', models.IntegerField()),
                ('head', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('repNum', models.IntegerField()),
                ('prNUm', models.IntegerField()),
                ('ctrNum', models.IntegerField()),
                ('readNum', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('replyId', models.IntegerField(primary_key=True, serialize=False)),
                ('crTime', models.IntegerField()),
                ('content', models.CharField(max_length=2000)),
                ('prNUm', models.IntegerField()),
                ('ctrNum', models.IntegerField()),
                ('readNum', models.IntegerField()),
                ('revID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mto', to='User.User')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Mfrom', to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyOfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Post.Post')),
                ('replyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='Post.Reply')),
            ],
        ),
    ]
