# Generated by Django 2.1.3 on 2018-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20181125_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userID',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='revID',
            new_name='revId',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='userID',
            new_name='userId',
        ),
        migrations.AlterField(
            model_name='post',
            name='ctrNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='prNUm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='readNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='repNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='ctrNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='prNUm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='readNum',
            field=models.IntegerField(default=0),
        ),
    ]
