# Generated by Django 2.1.3 on 2018-11-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20181125_2219'),
        ('Post', '0003_auto_20181125_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeOfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPr', models.BooleanField(default=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeOfReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPr', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='prNUm',
            new_name='prNum',
        ),
        migrations.AddField(
            model_name='judgeofreply',
            name='ReplyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.Reply'),
        ),
        migrations.AddField(
            model_name='judgeofreply',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User'),
        ),
    ]
