# Generated by Django 2.1.3 on 2018-12-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20181127_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='prNUm',
            new_name='prNum',
        ),
    ]
