# Generated by Django 2.1.3 on 2018-12-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20181209_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replyofpost',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='replyofpost',
            name='replyId',
        ),
        migrations.AddField(
            model_name='reply',
            name='postId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Post.Post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReplyOfPost',
        ),
    ]
