# Generated by Django 2.1.3 on 2018-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('snum', models.IntegerField()),
                ('checked', models.BooleanField(default=False)),
                ('QQ', models.IntegerField()),
            ],
        ),
    ]
